basePath: /api/v1
definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  models.Video:
    properties:
      description:
        type: string
      id:
        type: string
      path:
        type: string
      title:
        type: string
      video:
        type: string
    type: object
host: localhost:3003
info:
  contact: {}
  description: A streaming service API using Go and Gin framework, with Swagger documentation
    and ffmpeg integration.
  title: Go Streaming Service API
  version: "1.0"
paths:
  /users/:
    post:
      consumes:
      - application/json
      description: Save user in Db
      parameters:
      - description: User object containing all user details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - users
  /users/{UserId}:
    delete:
      description: Delete user by ID ni Db
      parameters:
      - description: User ID
        in: path
        name: Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Delete user by ID
      tags:
      - users
    get:
      description: Search user by ID in Db
      parameters:
      - description: User ID
        in: path
        name: Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get user by ID
      tags:
      - users
  /videos/:
    get:
      description: Upload a video file along with metadata (title and description)
        and save it to the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Video'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save a video
      tags:
      - videos
    post:
      consumes:
      - multipart/form-data
      description: Upload a video file along with metadata (title and description)
        and save it to the server.
      parameters:
      - description: Video Title
        in: formData
        name: title
        required: true
        type: string
      - description: Video Description
        in: formData
        name: description
        type: string
      - description: Video File
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Video'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save a video
      tags:
      - videos
swagger: "2.0"
